apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus # See: https://artifacthub.io/packages/helm/prometheus-community/prometheus/25.14.0
    version: 25.14.0
    repo: https://prometheus-community.github.io/helm-charts
    namespace: whirlpool
    releaseName: prometheus
    valuesInline:
      server:
        image:
          tag: v2.50.1 # See: https://github.com/grafana/grafana/issues/80185#issuecomment-1964049609
