apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ocean
  - ./sealedsecret.yaml

patches:
  - path: ./httproute_patch.yaml
  - path: ./policybinding_patch.yaml
  - target:
      kind: Job
      name: setup-origin-bucket
    path: ./job_patch.yaml
