---
apiVersion: sts.min.io/v1beta1
kind: PolicyBinding
metadata:
  name: mc-job
spec:
  application:
    namespace: playground-chloria-minio
---
apiVersion: sts.min.io/v1beta1
kind: PolicyBinding
metadata:
  name: chloria-backend
spec:
  application:
    namespace: playground-chloria
