---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.environment }}-archaist-cnpg
  labels:
    name: {{ .Values.environment }}-archaist-cnpg
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.environment }}-archaist-cnpg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://cloudnative-pg.github.io/charts
    - https://github.com/metalwhale/wave.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: {{ .Values.environment }}-archaist-cnpg
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.environment }}-archaist-cnpg
spec:
  project: {{ .Values.environment }}-archaist-cnpg
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts # Doc: https://github.com/cloudnative-pg/charts/tree/cluster-v0.2.0
      targetRevision: 0.2.0 # Doc: https://artifacthub.io/packages/helm/cloudnative-pg/cluster/0.2.0
      chart: cluster
      helm:
        releaseName: archaist-cnpg-cluster
        valuesObject:
          cluster:
            storage:
              storageClass: local-path
    - repoURL: https://github.com/metalwhale/wave.git
      targetRevision: main
      path: projects/archaist-cnpg/overlays/{{ .Values.environment }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.environment }}-archaist-cnpg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
