---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-cilium
spec:
  project: core
  sources:
    - repoURL: https://github.com/metalwhale/wave.git
      targetRevision: main
      ref: waveRepo
    - repoURL: https://helm.cilium.io/
      targetRevision: 1.16.5 # Doc: https://artifacthub.io/packages/helm/cilium/cilium/1.16.5
      chart: cilium
      helm:
        releaseName: cilium
        valuesObject:
          hubble:
            relay:
              enabled: true
        valueFiles:
          - $waveRepo/cores/cilium/base/{{ .Values.provider }}/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
