---
# See:
# - https://www.kubeflow.org/docs/components/notebooks/quickstart-guide/
# - https://github.com/kubeflow/kubeflow/blob/v1.7.0/components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: add-env-vars
spec:
  selector:
    matchLabels:
      add-env-var: "true"
  desc: "Add env vars"
  # Similar to `/applications/whirlpool/pipelines/app/weather_forecast/config.yaml` file
  # About the names of `env`, see https://github.com/metalwhale/weather-forecast-model repo.
  # About the values or secrets of `env`, see `/manifests/app/weather-forecast` dir of this repo.
  env:
    # Inputs
    - name: WP_INPUT_DATABASE_HOST
      value: learning-database-r.weather-forecast
    - name: WP_INPUT_DATABASE_PORT
      value: "5432"
    - name: WP_INPUT_DATABASE_DB
      value: app
    - name: WP_INPUT_DATABASE_USER
      value: model_trainer
    - name: WP_INPUT_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: learning-database
          key: model_trainer_password # See: `./secret.yaml` file
    # Tracking
    - name: WP_AIM_REPO
      value: aim://tracking-server.weather-forecast:53800 # See `/manifests/app/weather-forecast/@base/tracking.yaml` file
