apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  # Core
  - ../@components/core/argocd
  - ../@components/core/ingress-nginx
  # App
  - ../@components/app/sandbox

patches:
  # Core
  - path: ./core/argocd/application.yaml
  - path: ./core/ingress-nginx/application.yaml
  # App
  - path: ./app/sandbox/application.yaml
