apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argocd.yaml
  - ./newswaters.yaml
  - ./whirlpool.yaml
  - ./weather-forecast.yaml
  - ./vault.yaml
  - ./sandbox.yaml
