---
# Trust the operator's CA
# Doc: https://min.io/docs/minio/kubernetes/upstream/operations/cert-manager/cert-manager-operator.html
apiVersion: v1
kind: Secret
metadata:
  name: operator-ca-tls
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: core-minio-operator/operator-ca-tls
---
apiVersion: v1
kind: Secret
metadata:
  name: chloria-cnpg-cluster-init-auth
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: PLACEHOLDER # Ref: `../../overlays/${environment}/secret_patch.yaml` file
