---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-projects
spec:
  project: default
  sources:
    - repoURL: https://github.com/metalwhale/wave.git
      targetRevision: main
      path: projects/archaist-minio/source
      helm:
        valuesObject:
          environment: PLACEHOLDER # Ref: `./kustomization.yaml` file
    - repoURL: https://github.com/metalwhale/wave.git
      targetRevision: main
      path: projects/archaist-cnpg/source
      helm:
        valuesObject:
          environment: PLACEHOLDER # Ref: `./kustomization.yaml` file
    - repoURL: https://github.com/metalwhale/wave.git
      targetRevision: main
      path: projects/chloria-minio/source
      helm:
        valuesObject:
          environment: PLACEHOLDER # Ref: `./kustomization.yaml` file
    - repoURL: https://github.com/metalwhale/wave.git
      targetRevision: main
      path: projects/chloria-cnpg/source
      helm:
        valuesObject:
          environment: PLACEHOLDER # Ref: `./kustomization.yaml` file
    - repoURL: https://github.com/metalwhale/wave.git
      targetRevision: main
      path: projects/beach/source
      helm:
        valuesObject:
          environment: PLACEHOLDER # Ref: `./kustomization.yaml` file
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
