apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ./configmap.yaml
  - ../../base/ocean # Addons and cores
  - ./application.yaml # Projects

replacements:
  - source:
      kind: ConfigMap
      name: wave-config
      fieldPath: data.environment
    targets:
      - select:
          kind: Application
          name: wave-cores
        fieldPaths:
          - spec.sources.*.helm.valuesObject.environment
      - select:
          kind: Application
          name: wave-projects
        fieldPaths:
          - spec.sources.*.helm.valuesObject.environment
