apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ocean
  - ./configmap.yaml

patches:
  - path: ./clusterissuer_patch.yaml

replacements:
  - source:
      kind: ConfigMap
      name: core-global-config
      fieldPath: data.[hostname.argocd]
    targets:
      - select:
          kind: Gateway
          name: global
        fieldPaths:
          - spec.listeners.[name=argocd-.*].hostname
  - source:
      kind: ConfigMap
      name: core-global-config
      fieldPath: data.[hostname.archaist.minio]
    targets:
      - select:
          kind: Gateway
          name: global
        fieldPaths:
          - spec.listeners.[name=archaist-minio-.*].hostname
