apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

helmCharts:
  - name: external-secrets # See: https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets/0.9.13
    version: 0.9.13
    repo: https://charts.external-secrets.io
    namespace: external-secrets
    releaseName: eso
