apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  # See: https://kubernetes.github.io/ingress-nginx/deploy/#quick-start
  - name: ingress-nginx # See: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx/4.10.0
    version: 4.10.0
    repo: https://kubernetes.github.io/ingress-nginx
    namespace: ingress-nginx
    releaseName: ingress-nginx
