---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coral
spec:
  storage:
    storageClass: local-storage
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
