apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

helmCharts:
  - name: vault # See: https://artifacthub.io/packages/helm/hashicorp/vault/0.25.0
    version: 0.25.0
    repo: https://helm.releases.hashicorp.com
    namespace: vault
    releaseName: clam
    valuesInline:
      ui:
        enabled: "true"
        serviceType: NodePort
