---
apiVersion: v1
kind: Namespace
metadata:
  name: core-cnpg-operator
  labels:
    name: core-cnpg-operator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-cnpg-operator
spec:
  project: core
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts # Doc: https://github.com/cloudnative-pg/charts/tree/cloudnative-pg-v0.23.0
      targetRevision: 0.23.0 # Doc: https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg/0.23.0
      chart: cloudnative-pg
      helm:
        releaseName: cnpg-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: core-cnpg-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true # See: https://github.com/cloudnative-pg/charts/issues/325#issuecomment-2203812046
