---
# See:
# - https://argo-cd.readthedocs.io/en/release-2.9/operator-manual/ingress/#option-2-ssl-termination-at-ingress-controller
# - https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/
# - https://cert-manager.io/docs/tutorials/acme/nginx-ingress/#step-7---deploy-a-tls-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # See `/manifests/core/cert-manager/digitalocean/issuer.yaml` file
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # See: https://stackoverflow.com/a/63173789
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - argocd.wave.metalwhale.dev
      secretName: argocd-server-tls
  rules:
    - host: argocd.wave.metalwhale.dev
      http:
        paths:
          - path: / # See: `./configmap.yaml` file
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
