apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ocean
  - ./sealedsecret.yaml

patches:
  - target:
      kind: CiliumNetworkPolicy
      name: cnpg-cluster
    path: ./networkpolicy_patch.yaml
