apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-patch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      serviceAccountName: sandbox-app
      containers:
        - name: nginx
          image: nginx:1.25.2
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: sandbox
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
