---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  # Doc:
  # - https://cert-manager.io/v1.16-docs/configuration/acme/http01/#configuring-the-http-01-gateway-api-solver
  # - https://cert-manager.io/v1.16-docs/tutorials/acme/nginx-ingress/#step-6---configure-a-lets-encrypt-issuer
  # Note: These URLs doesn't exist yet, we should use the latest version
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: PLACEHOLDER # Ref: `../../overlays/${environment}/clusterissuer_patch.yaml` file
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: global
                namespace: core-global
                kind: Gateway
