---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: global
spec:
  gatewayClassName: cilium
  listeners:
    ##########
    # argocd
    ##########
    - name: argocd-http
      hostname: PLACEHOLDER # Ref: `../../overlays/${environment}/kustomization.yaml` file
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              name: argocd
