apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana # See: https://artifacthub.io/packages/helm/grafana/grafana/7.3.2
    version: 7.3.2
    repo: https://grafana.github.io/helm-charts
    namespace: whirlpool
    releaseName: monitor
    valuesInline:
      persistence:
        enabled: true
      grafana.ini:
        server:
          domain: grafana.whirlpool.wave.m-cloud.dev
      ingress:
        enabled: true
        hosts:
          - grafana.whirlpool.wave.m-cloud.dev

# See: https://marketplace.upbound.io/providers/grafana/provider-grafana/v0.10.2/managed-resources
resources:
  - ./secret.yaml
  - ./provider.yaml
  - ./organization.yaml
  - ./data-source.yaml
