#############################
# Secret for grafana provider
#############################
# About the content of the secret, see `./README.md` file
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-provider
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: grafana-provider
spec:
  provider:
    vault:
      server: http://clam-vault.vault.svc:8200
      path: clam
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: whirlpool-grafana-provider
          serviceAccountRef:
            name: grafana-provider
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-provider
spec:
  secretStoreRef:
    name: grafana-provider
    kind: SecretStore
  target:
    name: grafana-provider
  data:
    - secretKey: provider_credential
      remoteRef:
        key: whirlpool/grafana
        property: provider_credential
########################################
# Secret for weather forecast datasource
########################################
# About the content of the secret, see `/manifests/app/weather-forecast/README.md` file
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: weather-forecast-monitor
spec:
  provider:
    vault:
      server: http://clam-vault.vault.svc:8200
      path: clam
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: whirlpool-grafana-weather-forecast-monitor
          serviceAccountRef:
            name: monitor
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weather-forecast-learning-database
spec:
  secretStoreRef:
    name: weather-forecast-monitor
    kind: SecretStore
  target:
    name: weather-forecast-learning-database
  data:
    - secretKey: learning_database
      remoteRef:
        key: whirlpool/grafana/weather-forecast
        property: learning_database
