---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.environment }}-chloria-cnpg
  labels:
    name: {{ .Values.environment }}-chloria-cnpg
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.environment }}-chloria-cnpg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://cloudnative-pg.github.io/charts
    - https://github.com/metalwhale/wave.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: {{ .Values.environment }}-chloria-cnpg
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.environment }}-chloria-cnpg
spec:
  project: {{ .Values.environment }}-chloria-cnpg
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts # Doc: https://github.com/cloudnative-pg/charts/tree/cluster-v0.2.0
      targetRevision: 0.2.0 # Doc: https://artifacthub.io/packages/helm/cloudnative-pg/cluster/0.2.0
      chart: cluster
      helm:
        releaseName: chloria-cnpg-cluster
        valuesObject:
          cluster:
            # Doc:
            # - https://cloudnative-pg.io/documentation/1.25/bootstrap/#bootstrap-an-empty-cluster-initdb
            # - https://cloudnative-pg.io/documentation/1.25/cloudnative-pg.v1/#postgresql-cnpg-io-v1-BootstrapInitDB
            # Note:
            # - Operator chart version: `0.23.0` (Ref: `/cores/cnpg-operator/source/templates/application.yaml` file)
            # - Operator version: `1.25.0` (Ref: https://github.com/cloudnative-pg/charts/blob/cloudnative-pg-v0.23.0/charts/cloudnative-pg/Chart.yaml#L26)
            initdb:
              database: app
              owner: app
              secret:
                name: chloria-cnpg-cluster-init-auth
            storage:
              storageClass: local-path
    - repoURL: https://github.com/metalwhale/wave.git
      targetRevision: main
      path: projects/chloria-cnpg/overlays/{{ .Values.environment }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.environment }}-chloria-cnpg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
