---
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: MINIO_OPERATOR_STS_ENDPOINT
    value: https://sts.core-minio-operator.svc.cluster.local:4223/sts/playground-chloria-minio
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: MINIO_TENANT_ENDPOINT
    value: http://minio.playground-chloria-minio.svc.cluster.local
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: DATABASE_URL
    # The names of database and user are both `app`.
    # Ref: `/projects/chloria-cnpg/source/templates/application.yaml` file
    value: postgres://app:$(POSTGRESQL_PASSWORD)@chloria-cnpg-cluster-rw.playground-chloria-cnpg.svc/app
