---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chloria-secrets
spec:
  encryptedData:
    newsdata_api_key: AgC7nQI8/p/xDwFIoUPE1WrTZMbVlB5emgnWujmS3K0q49fyMKdTSqRbALvzbThOVh7bD9hEl+j2j8V0WhEpisI82bn+l7K1HlZ8sPxo5NUlEaAdfTPIcRqBCTzijSJw3BLYjCX3rPx797oIHW+2ZqlRjjPBejxVP2zPSwU24SdGWrFor2V3XS1nkaqa1rtj8wzl6AEO2KY9YZgDa4WCSyxuhbSByPjgZFbzkk1yImn6mxg8Kb5qbywTsXboMqCEXNP5mpQY8d9ft2dqU1HmKLl2IBFBnngIH+6SXNChgRio+xMtO6NXrTQ+gJLYz8Xa0UqPTu3pKwDe/qqZttjL8FhS52q9lP2DNJnfIPz3KOKRKdkLO0TCv7P3PwHX2xG6hjoZsLyJa5Nhc0Hwjue3mZMyKFGN7AuOLpnuUgSpVb283Fq3XmQQalJcxPqCif8uMs3q9D8YQ/BBQol5yohcB9ZhUgBg36PX8XXx+3dN+MiHWRlL8xdmIb7cU3b0rJ+D8GD+VO6e6HaasySSCY+IBVq8czqUwdYDIg8Pyth4w7JhJwDz7q81Kc2ouYoOBak6E46Al5DTHDRGKlpterK8H1LUZcsF0/yB2cLxIIQbt0Vl5I5Rm9k+gsyM9G8JaBukDiDhR3xAoptkm2sX1c54jILV+H8CY6+JC1k/SuFEBMNSOXLPUZk0UuFQblPVwN0IkUwWQxShH26zAc+OaLvZwfqL3YqOHQIxDrSWwgZs6BsHXa26+ewbbAJrSA==
