---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.environment }}-chloria
  labels:
    name: {{ .Values.environment }}-chloria
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.environment }}-chloria
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://github.com/metalwhale/wave.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: {{ .Values.environment }}-chloria
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.environment }}-chloria
spec:
  project: {{ .Values.environment }}-chloria
  sources:
    - repoURL: https://github.com/metalwhale/wave.git
      targetRevision: main
      path: projects/chloria/overlays/{{ .Values.environment }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.environment }}-chloria
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
