#######
# Vault
#######
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: HEAD
    path: manifests/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: "*"
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
############
# Newswaters
############
---
apiVersion: v1
kind: Namespace
metadata:
  name: newswaters
  labels:
    name: newswaters
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newswaters
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: HEAD
    path: manifests/newswaters
  destination:
    server: https://kubernetes.default.svc
    namespace: newswaters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: "*"
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
###########
# Whirlpool
###########
---
apiVersion: v1
kind: Namespace
metadata:
  name: whirlpool
  labels:
    name: whirlpool
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whirlpool
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: HEAD
    path: manifests/whirlpool
  destination:
    server: https://kubernetes.default.svc
    namespace: whirlpool
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
#########
# Sandbox
#########
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    name: sandbox
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: HEAD
    path: manifests/sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
