---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: HEAD
    path: manifests/kubeflow
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    # See: https://github.com/argoproj/argo-cd/issues/1487
    - group: admissionregistration.k8s.io
      kind: "*"
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
        - .webhooks[].rules
        - .webhooks[].failurePolicy
      managedFieldsManagers:
        - kube-controller-manager
    # See: https://github.com/argoproj/argo-cd/issues/2382
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jqPathExpressions:
        - .rules
      managedFieldsManagers:
        - clusterrole-aggregation-controller
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: inferenceservices.serving.kserve.io
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: HEAD
    path: manifests/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: "*"
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
---
apiVersion: v1
kind: Namespace
metadata:
  name: newswaters
  labels:
    name: newswaters
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newswaters
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: HEAD
    path: manifests/newswaters
  destination:
    server: https://kubernetes.default.svc
    namespace: newswaters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: "*"
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    name: sandbox
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandbox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: HEAD
    path: manifests/sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
