---
apiVersion: v1
kind: Namespace
metadata:
  name: core-reflector
  labels:
    name: core-reflector
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-reflector
spec:
  project: core
  sources:
    - repoURL: https://emberstack.github.io/helm-charts
      targetRevision: 7.1.288 # Doc: https://artifacthub.io/packages/helm/emberstack/reflector/7.1.288
      chart: reflector
      helm:
        releaseName: reflector
  destination:
    server: https://kubernetes.default.svc
    namespace: core-reflector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
