apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: model-trainer
---
# See: https://external-secrets.io/v0.9.13/provider/hashicorp-vault/#kubernetes-authentication
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: model-trainer
spec:
  provider:
    vault:
      server: http://clam-vault.vault.svc:8200
      path: clam
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: weather-forecast-model-trainer
          serviceAccountRef:
            name: model-trainer
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: learning-database
spec:
  secretStoreRef:
    name: model-trainer
    kind: SecretStore
  target:
    name: learning-database
  data:
    - secretKey: model_trainer_password
      remoteRef:
        key: weather-forecast/learning-database
        property: model_trainer_password
