---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://github.com/metalwhale/wave.git
    - https://helm.cilium.io/ # `cilium` core
    - https://argoproj.github.io/argo-helm # `argocd` core
    - https://charts.jetstack.io # `cert-manager` core
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
