---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: learning-database
spec:
  instances: 1
  storage:
    size: 8Gi
    resizeInUseVolumes: false # See: https://cloudnative-pg.io/documentation/1.20/storage/#recreating-storage
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: app
      owner: app
  postgresql:
    parameters:
      timezone: "Asia/Tokyo"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-whirlpool-to-learning-database
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: learning-database
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: whirlpool/role
                operator: Exists
      ports:
        - protocol: TCP
          port: 5432
