---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beach
  labels:
    app: beach
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: beach
  template:
    metadata:
      labels:
        app: beach
    spec:
      containers:
        - name: beach
          image: ubuntu:22.04
          env:
            - name: DATABASE_HOST
              value: coral-ro.newswaters.svc
            - name: DATABASE_DB
              value: app
            - name: DATABASE_USER
              value: app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coral-app
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          stdin: true
          tty: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echolocator-primary
  labels:
    app: echolocator-primary
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: echolocator-primary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: echolocator-primary
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: echolocator
          image: metalwhaledev/newswaters-echolocator:0.3.2
          imagePullPolicy: Always
          env:
            - name: ECHOLOCATOR_PORT
              value: "3000"
            - name: ECHOLOCATOR_THREADS
              value: "6"
            - name: ECHOLOCATOR_TEMP
              value: "0.4"
          command:
            - echolocator
          resources:
            limits:
              memory: "12Gi"
              cpu: "6000m"
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 30
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: echolocator-primary
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: echolocator-primary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echolocator-secondary
  labels:
    app: echolocator-secondary
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: echolocator-secondary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: echolocator-secondary
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: echolocator
          image: metalwhaledev/newswaters-echolocator:0.3.2
          imagePullPolicy: Always
          env:
            - name: ECHOLOCATOR_PORT
              value: "3000"
            - name: ECHOLOCATOR_THREADS
              value: "6"
            - name: ECHOLOCATOR_TEMP
              value: "0.4"
          command:
            - echolocator
          resources:
            limits:
              memory: "12Gi"
              cpu: "6000m"
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 30
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: echolocator-secondary
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: echolocator-secondary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whistler
  labels:
    app: whistler
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: whistler
  template:
    metadata:
      labels:
        app: whistler
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: whistler
          image: metalwhaledev/newswaters-whistler:0.2.6
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: coral-ro.newswaters.svc
            - name: DATABASE_DB
              value: app
            - name: DATABASE_USER
              value: app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coral-app
                  key: password
            - name: SEARCH_ENGINE_HOST
              value: search-engine.newswaters.svc
            - name: SEARCH_ENGINE_PORT
              value: "3000"
            - name: SEARCH_ENGINE_VECTOR_COLLECTION_NAMES
              value: item_summary,analysis_keyword
            - name: ECHOLOCATOR_HOST
              value: echolocator-primary.newswaters.svc
            - name: ECHOLOCATOR_PORT
              value: "3000"
            - name: WHISTLER_PORT
              value: "3000"
          command:
            - whistler
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: whistler
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: whistler
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whistler-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          # See: https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target
          - path: /newswaters-whistler(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: whistler
                port:
                  number: 3000
