---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beach
  labels:
    app: beach
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beach
  template:
    metadata:
      labels:
        app: beach
    spec:
      containers:
        - name: beach
          image: ubuntu:22.04
          env:
            - name: DATABASE_HOST
              value: coral-ro.newswaters.svc
            - name: DATABASE_DB
              value: app
            - name: DATABASE_USER
              value: app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coral-app
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          stdin: true
          tty: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echolocator
  labels:
    app: echolocator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echolocator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: echolocator
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: echolocator
          image: metalwhaledev/newswaters-echolocator:0.3.0
          imagePullPolicy: Always
          env:
            - name: ECHOLOCATOR_PORT
              value: "3000"
            - name: ECHOLOCATOR_THREADS
              value: "6"
            - name: ECHOLOCATOR_TEMP
              value: "0.4"
          command:
            - echolocator
          resources:
            limits:
              memory: "12Gi"
              cpu: "6000m"
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 30
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: echolocator
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: echolocator
---
apiVersion: batch/v1
kind: Job
metadata:
  name: skimmer-migration
spec:
  template:
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: skimmer-migration
          image: metalwhaledev/newswaters-skimmer:0.3.3
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: coral-rw.newswaters.svc
            - name: DATABASE_DB
              value: app
            - name: DATABASE_USER
              value: app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coral-app
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_DB)"
          command:
            - diesel
            - migration
            - run
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skimmer-collect-items
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  concurrencyPolicy: Replace
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            # See: https://github.com/metalwhale/newswaters
            - name: skimmer-collect-items
              image: metalwhaledev/newswaters-skimmer:0.3.3
              imagePullPolicy: Always
              env:
                - name: DATABASE_HOST
                  value: coral-rw.newswaters.svc
                - name: DATABASE_DB
                  value: app
                - name: DATABASE_USER
                  value: app
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: coral-app
                      key: password
                - name: SKIMMER_IS_JOB
                  value: "true"
                - name: SKIMMER_ITEMS_NUM
                  value: "100000"
                - name: SKIMMER_PERMITS_NUM
                  value: "50"
                - name: SKIMMER_BATCH_SIZE
                  value: "1000"
              command:
                - skimmer
                - collect_items
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "500m"
                limits:
                  memory: "1Gi"
                  cpu: "2000m"
              securityContext:
                runAsUser: 1000
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skimmer-collect-item-urls
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  concurrencyPolicy: Replace
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            # See: https://github.com/metalwhale/newswaters
            - name: skimmer-collect-item-urls
              image: metalwhaledev/newswaters-skimmer:0.3.3
              imagePullPolicy: Always
              env:
                - name: DATABASE_HOST
                  value: coral-rw.newswaters.svc
                - name: DATABASE_DB
                  value: app
                - name: DATABASE_USER
                  value: app
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: coral-app
                      key: password
                - name: SKIMMER_IS_JOB
                  value: "true"
                - name: SKIMMER_ITEM_URLS_NUM
                  value: "100000"
                - name: SKIMMER_PERMITS_NUM
                  value: "10"
                - name: SKIMMER_BATCH_SIZE
                  value: "100000"
              command:
                - skimmer
                - collect_item_urls
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "1000m"
                limits:
                  memory: "8Gi"
                  cpu: "2000m"
              securityContext:
                runAsUser: 1000
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skimmer-consume-top-stories
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  concurrencyPolicy: Replace
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            # See: https://github.com/metalwhale/newswaters
            - name: skimmer-consume-top-stories
              image: metalwhaledev/newswaters-skimmer:0.3.3
              imagePullPolicy: Always
              env:
                - name: DATABASE_HOST
                  value: coral-rw.newswaters.svc
                - name: DATABASE_DB
                  value: app
                - name: DATABASE_USER
                  value: app
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: coral-app
                      key: password
                - name: ECHOLOCATOR_HOST
                  value: echolocator.newswaters.svc
                - name: ECHOLOCATOR_PORT
                  value: "3000"
                - name: SKIMMER_IS_JOB
                  value: "true"
                - name: SKIMMER_TOP_STORIES_NUM
                  value: "30"
                - name: SKIMMER_TEXT_MIN_LINE_LENGTH
                  value: "80"
                - name: SKIMMER_TEXT_MAX_TOTAL_LENGTH
                  value: "4800"
              command:
                - skimmer
                - consume_top_stories
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "500m"
                limits:
                  memory: "2Gi"
                  cpu: "1000m"
              securityContext:
                runAsUser: 1000
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skimmer-consume-top-story-summaries
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  concurrencyPolicy: Replace
  schedule: "15,45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            # See: https://github.com/metalwhale/newswaters
            - name: skimmer-consume-top-story-summaries
              image: metalwhaledev/newswaters-skimmer:0.3.3
              imagePullPolicy: Always
              env:
                - name: DATABASE_HOST
                  value: coral-rw.newswaters.svc
                - name: DATABASE_DB
                  value: app
                - name: DATABASE_USER
                  value: app
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: coral-app
                      key: password
                - name: SEARCH_ENGINE_HOST
                  value: search-engine.newswaters.svc
                - name: SEARCH_ENGINE_PORT
                  value: "3000"
                - name: ECHOLOCATOR_HOST
                  value: echolocator.newswaters.svc
                - name: ECHOLOCATOR_PORT
                  value: "3000"
                - name: SKIMMER_IS_JOB
                  value: "true"
                - name: SKIMMER_TOP_STORY_SUMMARIES_NUM
                  value: "300"
              command:
                - skimmer
                - consume_top_story_summaries
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "500m"
                limits:
                  memory: "2Gi"
                  cpu: "1000m"
              securityContext:
                runAsUser: 1000
          restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whistler
  labels:
    app: whistler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whistler
  template:
    metadata:
      labels:
        app: whistler
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: whistler
          image: metalwhaledev/newswaters-whistler:0.2.1
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: coral-ro.newswaters.svc
            - name: DATABASE_DB
              value: app
            - name: DATABASE_USER
              value: app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coral-app
                  key: password
            - name: SEARCH_ENGINE_HOST
              value: search-engine.newswaters.svc
            - name: SEARCH_ENGINE_PORT
              value: "3000"
            - name: ECHOLOCATOR_HOST
              value: echolocator.newswaters.svc
            - name: ECHOLOCATOR_PORT
              value: "3000"
            - name: WHISTLER_PORT
              value: "3000"
          command:
            - whistler
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: whistler
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: whistler
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whistler-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          # See: https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target
          - path: /newswaters-whistler(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: whistler
                port:
                  number: 3000
