---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coral
spec:
  instances: 2
  storage:
    size: 48Gi
    storageClass: local-storage
    resizeInUseVolumes: false # See: https://cloudnative-pg.io/documentation/1.20/storage/#recreating-storage
  bootstrap:
    initdb:
      database: app
      owner: app
  postgresql:
    parameters:
      timezone: "Asia/Tokyo"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          # OCEAN: I don't want to claim large storages on control-plane nodes
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
---
# OCEAN: For testing purpose
apiVersion: v1
kind: Service
metadata:
  name: coral-ro-static
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 30000
  selector:
    cnpg.io/cluster: coral
    role: replica
  type: NodePort
