---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-migration
spec:
  template:
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: job-migration
          image: metalwhaledev/newswaters-job:0.2.0
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: coral-rw.newswaters.svc
            - name: DATABASE_DB
              value: app
            - name: DATABASE_USER
              value: app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coral-app
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_DB)"
          command:
            - diesel
            - migration
            - run
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-collect-items
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  concurrencyPolicy: Replace
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            # See: https://github.com/metalwhale/newswaters
            - name: job-collect-items
              image: metalwhaledev/newswaters-job:0.2.0
              imagePullPolicy: Always
              env:
                - name: DATABASE_HOST
                  value: coral-rw.newswaters.svc
                - name: DATABASE_DB
                  value: app
                - name: DATABASE_USER
                  value: app
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: coral-app
                      key: password
                - name: JOB_COLLECT_ITEMS_NUM
                  value: "100000"
                - name: JOB_PERMITS_NUM
                  value: "50"
                - name: JOB_CHUNK_SIZE
                  value: "1000"
              command:
                - newswaters-job
                - collect_items
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "500m"
                limits:
                  memory: "1Gi"
                  cpu: "2000m"
              securityContext:
                runAsUser: 1000
          restartPolicy: Never
  successfulJobsHistoryLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-collect-item-urls
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  concurrencyPolicy: Replace
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            # See: https://github.com/metalwhale/newswaters
            - name: job-collect-item-urls
              image: metalwhaledev/newswaters-job:0.2.0
              imagePullPolicy: Always
              env:
                - name: DATABASE_HOST
                  value: coral-rw.newswaters.svc
                - name: DATABASE_DB
                  value: app
                - name: DATABASE_USER
                  value: app
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: coral-app
                      key: password
                - name: JOB_COLLECT_ITEM_URLS_NUM
                  value: "100000"
                - name: JOB_PERMITS_NUM
                  value: "10"
                - name: JOB_CHUNK_SIZE
                  value: "100000"
              command:
                - newswaters-job
                - collect_item_urls
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "1000m"
                limits:
                  memory: "8Gi"
                  cpu: "2000m"
              securityContext:
                runAsUser: 1000
          restartPolicy: Never
  successfulJobsHistoryLimit: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-summarize-and-analyze
  labels:
    app: job-summarize-and-analyze
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: job-summarize-and-analyze
  template:
    metadata:
      labels:
        app: job-summarize-and-analyze
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: job-summarize-and-analyze
          image: metalwhaledev/newswaters-job:0.2.0
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: coral-rw.newswaters.svc
            - name: DATABASE_DB
              value: app
            - name: DATABASE_USER
              value: app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coral-app
                  key: password
            - name: INFERENCE_HOST
              value: inference-primary.newswaters.svc
            - name: INFERENCE_PORT
              value: "3000"
            - name: JOB_SUMMARIZE_TEXTS_NUM
              value: "15"
            - name: JOB_ANALYZE_COMMENT_TEXTS_NUM
              value: "30"
            - name: JOB_INSTRUCT_RANDOM_PASSAGE_WORDS_RETENTION_RATE
              value: "0.2"
          command:
            - /bin/sh
            - -c
            - >
              newswaters-job summarize_texts &&
              newswaters-job analyze_comment_texts
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          securityContext:
            runAsUser: 1000
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-embed
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  concurrencyPolicy: Replace
  schedule: "0,30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            # See: https://github.com/metalwhale/newswaters
            - name: job-embed
              image: metalwhaledev/newswaters-job:0.2.0
              imagePullPolicy: Always
              env:
                - name: DATABASE_HOST
                  value: coral-rw.newswaters.svc
                - name: DATABASE_DB
                  value: app
                - name: DATABASE_USER
                  value: app
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: coral-app
                      key: password
                - name: SEARCH_ENGINE_HOST
                  value: search-engine.newswaters.svc
                - name: SEARCH_ENGINE_PORT
                  value: "3000"
                - name: SEARCH_ENGINE_VECTOR_SUMMARY_COLLECTION_NAME
                  value: item_summary
                - name: INFERENCE_HOST
                  value: inference-secondary.newswaters.svc
                - name: INFERENCE_PORT
                  value: "3000"
                - name: JOB_EMBED_SUMMARIES_NUM
                  value: "1000000"
                - name: JOB_CHUNK_SIZE
                  value: "50"
              command:
                - /bin/sh
                - -c
                - newswaters-job embed_summaries
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "500m"
                limits:
                  memory: "2Gi"
                  cpu: "1000m"
              securityContext:
                runAsUser: 1000
          restartPolicy: Never
  successfulJobsHistoryLimit: 1
