---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-engine-vector-storage
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-engine-text-storage
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine
  labels:
    app: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: search-engine
          image: metalwhaledev/newswaters-search-engine:0.2.0
          imagePullPolicy: Always
          env:
            - name: SEARCH_ENGINE_PORT
              value: "3000"
            - name: SEARCH_ENGINE_VECTOR_HOST
              value: localhost
            - name: SEARCH_ENGINE_VECTOR_PORT
              value: "6334"
            - name: SEARCH_ENGINE_VECTOR_COLLECTION
              value: "app"
            - name: SEARCH_ENGINE_VECTOR_SIZE
              value: "768" # See: https://huggingface.co/jinaai/jina-embeddings-v2-base-en/blob/d411fe9/config.json#L18
            - name: SEARCH_ENGINE_TEXT_STORAGE_PATH
              value: /var/lib/tantivy/storage
          volumeMounts:
            - mountPath: /var/lib/tantivy/storage
              name: text-storage
          command:
            - search-engine
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
        - name: search-engine-vector
          image: qdrant/qdrant:v1.6.1
          env:
            - name: QDRANT__SERVICE__GRPC_PORT
              value: "6334"
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /qdrant/storage
              name: vector-storage
      volumes:
        - name: vector-storage
          persistentVolumeClaim:
            claimName: search-engine-vector-storage
        - name: text-storage
          persistentVolumeClaim:
            claimName: search-engine-text-storage
---
apiVersion: v1
kind: Service
metadata:
  name: search-engine
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: search-engine
