---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-engine-vector-storage
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine
  labels:
    app: search-engine
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: search-engine
          image: metalwhaledev/newswaters-search-engine:0.3.0
          imagePullPolicy: Always
          env:
            - name: SEARCH_ENGINE_PORT
              value: "3000"
            - name: SEARCH_ENGINE_VECTOR_HOST
              value: localhost
            - name: SEARCH_ENGINE_VECTOR_PORT
              value: "6334"
            - name: SEARCH_ENGINE_VECTOR_COLLECTION_NAMES
              value: item_summary
          command:
            - search-engine
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
        - name: search-engine-vector
          image: qdrant/qdrant:v1.6.1
          env:
            - name: QDRANT__SERVICE__GRPC_PORT
              value: "6334"
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /qdrant/storage
              name: vector-storage
      volumes:
        - name: vector-storage
          persistentVolumeClaim:
            claimName: search-engine-vector-storage
---
apiVersion: v1
kind: Service
metadata:
  name: search-engine
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: search-engine
