apiVersion: apps/v1
kind: Deployment
metadata:
  name: skimmer-item-urls-patch
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skimmer-item-urls
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: skimmer-item-urls
    spec:
      containers:
        # See: https://github.com/metalwhale/newswaters
        - name: skimmer-item-urls
          image: metalwhaledev/newswaters-skimmer:0.1.0
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: coral-rw.newswaters.svc
            - name: DATABASE_DB
              value: app
            - name: DATABASE_USER
              value: app
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coral-app
                  key: password
            - name: SKIMMER_ITEMS_NUM
              value: "2000000"
            - name: SKIMMER_PERMITS_NUM
              value: "20"
            - name: SKIMMER_BATCH_SIZE
              value: "50000"
          command:
            - skimmer
            - item_urls
          resources:
            requests:
              memory: "8Gi"
              cpu: "2000m"
            limits:
              memory: "16Gi"
              cpu: "4000m"
          securityContext:
            runAsUser: 1000
