---
apiVersion: v1
kind: Service
metadata:
  name: beach
spec:
  selector:
    app: beach
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: island
spec:
  selector:
    app: island
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
