---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clam-vault
  namespace: vault
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-storage
