---
# Doc: https://min.io/docs/minio/kubernetes/upstream/operations/cert-manager/cert-manager-operator.html#id2
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-operator-ca-certificate
spec:
  isCA: true
  commonName: operator
  secretName: operator-ca-tls
  duration: 70128h # 8y
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io
---
# Doc: https://min.io/docs/minio/kubernetes/upstream/operations/cert-manager/cert-manager-operator.html#use-the-secret-to-create-the-issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: minio-operator-ca-issuer
spec:
  ca:
    secretName: operator-ca-tls
---
# Doc: https://min.io/docs/minio/kubernetes/upstream/operations/cert-manager/cert-manager-operator.html#use-the-secret-to-create-the-issuer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sts-certmanager-cert
spec:
  dnsNames:
    - sts
    - sts.core-minio-operator.svc
    - sts.core-minio-operator.svc.cluster.local # Replace cluster.local with the value for your domain.
  secretName: sts-tls
  issuerRef:
    name: minio-operator-ca-issuer
