---
# Trust the tenant's CA in MinIO Operator
# Doc: https://min.io/docs/minio/kubernetes/upstream/operations/cert-manager/cert-manager-tenants.html#trust-the-tenant-s-ca-in-minio-operator
apiVersion: v1
kind: Secret
metadata:
  name: operator-ca-tls-archaist
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: PLACEHOLDER # Replaced later. Ref: `../../overlays/${environment}/secret_patch.yaml` file
