---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.environment }}-beach
spec:
  project: {{ .Values.environment }}-beach
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: main
    path: projects/beach/overlays/{{ .Values.environment }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.environment }}-beach
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
