argocd:
  source:
    repo:
      url: https://github.com/metalwhale/wave
      revision: main
      path: ./manifests/whirlpool/deploykf
# See: https://www.deploykf.org/guides/getting-started/#kubernetes-configurations
deploykf_opt:
  deploykf_minio:
    persistence:
      storageClass: local-storage
  deploykf_mysql:
    persistence:
      storageClass: local-storage
deploykf_core:
  deploykf_istio_gateway:
    gateway:
      # OCEAN: For local testing
      # See:
      # - https://www.deploykf.org/guides/getting-started/#expose-the-gateway, "Expose Gateway - Local Testing"
      # - https://github.com/deployKF/deployKF/blob/v0.1.3/sample-values.yaml#L241-L242
      ports:
        http: 8080
        https: 8443
  deploykf_profiles_generator:
    users:
      - id: whale
        email: "whale@metalwhale.dev"
      - id: orca
        email: "orca@metalwhale.dev"
      - id: dolphin
        email: "dolphin@metalwhale.dev"
    groups:
      - id: weather-forecast
        users:
          - dolphin
    profiles:
      - name: weather-forecast
        members:
          - group: weather-forecast
            access:
              role: edit
              notebooksAccess: true
  deploykf_profiles_generator.profileDefaults.ownerEmail: "whale@metalwhale.dev"
  deploykf_auth:
    dex:
      # OCEAN: Dummy users' passwords
      staticPasswords:
        - email: "whale@metalwhale.dev"
          password:
            value: "whale"
        - email: "orca@metalwhale.dev"
          password:
            value: "orca"
        - email: "dolphin@metalwhale.dev"
          password:
            value: "dolphin"

kubeflow_tools:
  notebooks:
    enabled: true
    spawnerFormDefaults:
      imageGroupOne:
        options:
          - kubeflownotebookswg/codeserver-python:v1.7.0
          - metalwhaledev/kubeflow-notebook-codeserver:v1.8.0
        value: metalwhaledev/kubeflow-notebook-codeserver:v1.8.0
