# About the content of the secret, see `./README.md` file
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-provider
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: grafana-provider
spec:
  provider:
    vault:
      server: http://clam-vault.vault.svc:8200
      path: clam
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: whirlpool-grafana-provider
          serviceAccountRef:
            name: grafana-provider
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-provider
spec:
  secretStoreRef:
    name: grafana-provider
    kind: SecretStore
  target:
    name: grafana-provider
  data:
    - secretKey: provider_credential
      remoteRef:
        key: whirlpool/grafana
        property: provider_credential
