apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  # Core
  - ../@components/core/argocd
  - ../@components/core/external-secrets
  - ../@components/core/vault
  - ../@components/core/tembo
  - ../@components/core/crossplane
  - ../@components/core/cilium
  - ../@components/core/whirlpool
  # App
  - ../@components/app/newswaters
  - ../@components/app/weather-forecast
  - ../@components/app/sandbox

resources:
  - ./ingress.yaml
  - ./storage.yaml
  - ./dashboard.yaml

patches:
  # Core
  - path: ./core/argocd/application.yaml
  - path: ./core/external-secrets/application.yaml
  - path: ./core/vault/application.yaml
  - path: ./core/tembo/application.yaml
  - path: ./core/crossplane/application.yaml
  - path: ./core/cilium/application.yaml
  - path: ./core/whirlpool/application.yaml
  # App
  - path: ./app/newswaters/application.yaml
  - path: ./app/weather-forecast/application.yaml
  - path: ./app/sandbox/application.yaml
