---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: whirlpool-weather-forecast
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://github.com/metalwhale/wave.git
  destinations:
    - namespace: whirlpool-weather-forecast # Created when generating profile at /packages/deploykf/custom-values.yaml
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whirlpool-weather-forecast
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: whirlpool-weather-forecast
  source:
    repoURL: https://github.com/metalwhale/wave.git
    targetRevision: HEAD
    path: manifests/whirlpool-weather-forecast
  destination:
    server: https://kubernetes.default.svc
    namespace: whirlpool-weather-forecast
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
